src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 * @ORM\Table(name="empsys.cliente")
 */
class Cliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $razao_social;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nome_fantasia;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $cnpj;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ativo;

    /**
     * @ORM\OneToMany(targetEntity=Local::class, mappedBy="cliente")
     */
    private $local;

    /**
     * @ORM\OneToMany(targetEntity=ListaEmpilhadeira::class, mappedBy="cliente")
     */
    private $empilhadeira;

    public function __construct()
    {
        $this->local = new ArrayCollection();
        $this->empilhadeira = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRazaoSocial(): ?string
    {
        return $this->razao_social;
    }

    public function setRazaoSocial(string $razao_social): self
    {
        $this->razao_social = $razao_social;

        return $this;
    }

    public function getNomeFantasia(): ?string
    {
        return $this->nome_fantasia;
    }

    public function setNomeFantasia(?string $nome_fantasia): self
    {
        $this->nome_fantasia = $nome_fantasia;

        return $this;
    }

    public function getCnpj(): ?string
    {
        return $this->cnpj;
    }

    public function setCnpj(string $cnpj): self
    {
        $this->cnpj = $cnpj;

        return $this;
    }

    public function getAtivo(): ?bool
    {
        return $this->ativo;
    }

    public function setAtivo(bool $ativo): self
    {
        $this->ativo = $ativo;

        return $this;
    }

    /**
     * @return Collection<int, Local>
     */
    public function getLocal(): Collection
    {
        return $this->local;
    }

    public function addLocal(Local $local): self
    {
        if (!$this->local->contains($local)) {
            $this->local[] = $local;
            $local->setCliente($this);
        }

        return $this;
    }

    public function removeLocal(Local $local): self
    {
        if ($this->local->removeElement($local)) {
            // set the owning side to null (unless already changed)
            if ($local->getCliente() === $this) {
                $local->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ListaEmpilhadeira>
     */
    public function getEmpilhadeira(): Collection
    {
        return $this->empilhadeira;
    }

    public function addEmpilhadeira(ListaEmpilhadeira $empilhadeira): self
    {
        if (!$this->empilhadeira->contains($empilhadeira)) {
            $this->empilhadeira[] = $empilhadeira;
            $empilhadeira->setCliente($this);
        }

        return $this;
    }

    public function removeEmpilhadeira(ListaEmpilhadeira $empilhadeira): self
    {
        if ($this->empilhadeira->removeElement($empilhadeira)) {
            // set the owning side to null (unless already changed)
            if ($empilhadeira->getCliente() === $this) {
                $empilhadeira->setCliente(null);
            }
        }

        return $this;
    }
}

src/Entity/Cliente/Cliente.php
<?php

namespace App\Entity\Cliente;

use App\Entity\Local;
use App\Entity\Maquina\ListaEmpilhadeira;
use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 * @ORM\Table(name="empsys.cliente")
 */
class Cliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $razao_social;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nome_fantasia;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $cnpj;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ativo;

    /**
     * @ORM\OneToMany(targetEntity=Local::class, mappedBy="cliente")
     */
    private $local;

    /**
     * @ORM\OneToMany(targetEntity=ListaEmpilhadeira::class, mappedBy="cliente")
     */
    private $empilhadeira;

    public function __construct()
    {
        $this->local = new ArrayCollection();
        $this->empilhadeira = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRazaoSocial(): ?string
    {
        return $this->razao_social;
    }

    public function setRazaoSocial(string $razao_social): self
    {
        $this->razao_social = $razao_social;

        return $this;
    }

    public function getNomeFantasia(): ?string
    {
        return $this->nome_fantasia;
    }

    public function setNomeFantasia(?string $nome_fantasia): self
    {
        $this->nome_fantasia = $nome_fantasia;

        return $this;
    }

    public function getCnpj(): ?string
    {
        return $this->cnpj;
    }

    public function setCnpj(string $cnpj): self
    {
        $this->cnpj = $cnpj;

        return $this;
    }

    public function getAtivo(): ?bool
    {
        return $this->ativo;
    }

    public function setAtivo(bool $ativo): self
    {
        $this->ativo = $ativo;

        return $this;
    }

    /**
     * @return Collection<int, Local>
     */
    public function getLocal(): Collection
    {
        return $this->local;
    }

    public function addLocal(Local $local): self
    {
        if (!$this->local->contains($local)) {
            $this->local[] = $local;
            $local->setCliente($this);
        }

        return $this;
    }

    public function removeLocal(Local $local): self
    {
        if ($this->local->removeElement($local)) {
            // set the owning side to null (unless already changed)
            if ($local->getCliente() === $this) {
                $local->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ListaEmpilhadeira>
     */
    public function getEmpilhadeira(): Collection
    {
        return $this->empilhadeira;
    }

    public function addEmpilhadeira(ListaEmpilhadeira $empilhadeira): self
    {
        if (!$this->empilhadeira->contains($empilhadeira)) {
            $this->empilhadeira[] = $empilhadeira;
            $empilhadeira->setCliente($this);
        }

        return $this;
    }

    public function removeEmpilhadeira(ListaEmpilhadeira $empilhadeira): self
    {
        if ($this->empilhadeira->removeElement($empilhadeira)) {
            // set the owning side to null (unless already changed)
            if ($empilhadeira->getCliente() === $this) {
                $empilhadeira->setCliente(null);
            }
        }

        return $this;
    }
}

src/Form/ClienteType.php
<?php

namespace App\Form;

use App\Entity\Cliente\Cliente;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('razao_social', TextType::class, [
                'required' => true,
                'label' => 'Razão Social:*',
            ])
            ->add('nome_fantasia', TextType::class, [
                'required' => true,
                'label' => 'Nome Fantasia:*',
            ])
            ->add('cnpj', TextType::class, [
                'required' => true,
                'label' => 'CNPJ:*',
            ])
            ->add('ativo');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cliente::class,
        ]);
    }
}

src/Controller/ClienteController.php
<?php

namespace App\Controller;

use App\Entity\Cliente\Cliente;
use App\Form\ClienteType;
use App\Repository\ClienteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/cliente")
 */
class ClienteController extends AbstractController
{
    /**
     * @Route("/", name="cliente_index", methods={"GET"})
     */
    public function index(ClienteRepository $clienteRepository): Response
    {
        return $this->render('cliente/index.html.twig', [
            'clientes' => $clienteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="cliente_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ClienteRepository $clienteRepository): Response
    {
        $cliente = new Cliente();
        $form = $this->createForm(ClienteType::class, $cliente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clienteRepository->add($cliente);
            return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cliente/new.html.twig', [
            'cliente' => $cliente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cliente_show", methods={"GET"})
     */
    public function show(Cliente $cliente): Response
    {
        return $this->render('cliente/show.html.twig', [
            'cliente' => $cliente,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="cliente_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Cliente $cliente, ClienteRepository $clienteRepository): Response
    {
        $form = $this->createForm(ClienteType::class, $cliente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clienteRepository->add($cliente);
            return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cliente/edit.html.twig', [
            'cliente' => $cliente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cliente_delete", methods={"POST"})
     */
    public function delete(Request $request, Cliente $cliente, ClienteRepository $clienteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cliente->getId(), $request->request->get('_token'))) {
            $clienteRepository->remove($cliente);
        }

        return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cliente/_delete_form.html.twig
<form method="post" action="{{ path('cliente_delete', {'id': cliente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cliente.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cliente/_form.html.twig
{{ form_start(form) }}
<div class="container col-md-12">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h5 class="mb-0">Cadastro de Cliente</h5>
        </div>

        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ form_row(form.razao_social) }}
                </div>
                <div class="form-group col-md-4">
                    {{ form_row(form.cnpj) }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-8">
                    {{ form_row(form.nome_fantasia) }}
                </div>
                <div class="form-group col-md-4">
                    {{ form_row(form.ativo) }}
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between">
                <a href="{{ path('cliente_index') }}" class="btn btn-info">
                    Voltar
                </a>
                <button type="submit" class="btn btn-success">
                    {{ button_label|default('Salvar') }}
                </button>
            </div>
        </div>


    </div>
</div>
{{ form_widget(form._token) }}
{{ form_end(form, {'render_rest': false}) }}

templates/cliente/edit.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <br>
    {#<div class="container-fluid">#}
    {{ include('cliente/_form.html.twig') }}
    {#    </div#}
{% endblock %}

templates/cliente/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <br>
    <div class="container col-md-12">

        <div class="card shadow-sm">

            <div class="card-header bg-primary text-white">
                <h5 class="mb-0">Clientes</h5>
            </div>
            <div class="card-header d-flex justify-content-between">
                <a href="{{ path('lista_empilhadeira_new') }}" class="btn btn-success">
                    Novo cliente
                </a>
                <a href="{{ path('app_dashboard') }}" class="btn btn-info">
                    Voltar
                </a>
            </div>
            <div class="card-body p-3">
                <table class="table table-striped table-hover w-100">
                    <thead class="thead-light">
                    <tr>
                        <th style="width: 5%">ID</th>            {# col-md-1 ~ 1/12 = 8.33%, ajustei para 5% pra ser mais compacto #}
                        <th style="width: 20%">Razão Social</th>   {# col-md-1 #}
                        <th style="width: 20%">Nome Fantasia</th>      {# col-md-2 #}
                        <th style="width: 15%">CNPJ</th> {# col-md-1 #}
                        <th style="width: 10%">Ativo</th> {# col-md-4 #}
                        <th style="width: 15%">Ações</th>        {# col-md-2 #}
                    </tr>
                    </thead>
                    <tbody>
                    {% for cliente in clientes %}
                        <tr>
                            <td>{{ cliente.id }}</td>
                            <td>{{ cliente.razaoSocial }}</td>
                            <td>{{ cliente.nomeFantasia }}</td>
                            <td>{{ cliente.cnpj }}</td>
                            <td>{{ cliente.ativo }}</td>
                            {#                            <td>{{ lista_empilhadeira.caracteristicas }}</td>#}
                            {#                            <td>{{ lista_empilhadeira.aplicacoes }}</td>#}
                            <td>
                                <a href="{{ path('cliente_show', {'id': cliente.id}) }}" class="btn btn-sm btn-outline-primary">Ver</a>
                                <a href="{{ path('cliente_edit', {'id': cliente.id}) }}" class="btn btn-sm btn-outline-secondary">Editar</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7" class="text-center">Nenhum registro encontrado</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/cliente/new.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <br>
    {#<div class="container-fluid">#}
    {{ include('cliente/_form.html.twig') }}
    {#    </div#}
{% endblock %}

templates/cliente/show.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <br>
    <div class="container col-md-12">
        <div class="card shadow-sm">
            <div class="card-header bg-primary text-white">
                <h5 class="mb-0">Detalhes do Cliente</h5>
            </div>

            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-md-2 font-weight-bold">ID:</div>
                    <div class="col-md-10">{{ cliente.id }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-2 font-weight-bold">Fabricante:</div>
                    <div class="col-md-10">{{ cliente.razaoSocial }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-2 font-weight-bold">Modelo:</div>
                    <div class="col-md-10">{{ cliente.nomeFantasia }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-2 font-weight-bold">Carga Total (kg):</div>
                    <div class="col-md-10">{{ cliente.cnpj }} kg</div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-2 font-weight-bold">Características:</div>
                    <div class="col-md-10">{{ cliente.ativo }}</div>
                </div>
            </div>

            <div class="card-footer d-flex justify-content-between">
                <a href="{{ path('cliente_index') }}" class="btn btn-info">Voltar</a>
                <a href="{{ path('cliente_edit', {'id': cliente.id}) }}" class="btn btn-warning">Editar</a>
            </div>
        </div>
    </div>

{% endblock %}